# Generated by Django 4.1.3 on 2022-11-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file_name", models.CharField(max_length=200)),
                ("audio_file", models.FileField(blank=True, upload_to="audio")),
            ],
        ),
    ]
